# Generated by Django 6.0.6 on 2026-07-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_widen_report_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='投入金额（元）', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='holding_days',
            field=models.IntegerField(blank=True, help_text='持有天数', null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='盈亏金额（元），正值为盈利，负值为亏损', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='shares_held',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='持有份额', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
